// AUTO-GENERATED — augments Vue's GlobalComponents so components registered by
// `app.use(VibeUI)` are typed in templates (props/events/slots) under vue-tsc/Volar.
// Regenerate from the app.component(...) calls in src/components/index.ts on changes.
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VibeAccordion: typeof import('./components')['VibeAccordion']
    VibeAlert: typeof import('./components')['VibeAlert']
    VibeAutocomplete: typeof import('./components')['VibeAutocomplete']
    VibeBadge: typeof import('./components')['VibeBadge']
    VibeBreadcrumb: typeof import('./components')['VibeBreadcrumb']
    VibeButton: typeof import('./components')['VibeButton']
    VibeButtonGroup: typeof import('./components')['VibeButtonGroup']
    VibeCard: typeof import('./components')['VibeCard']
    VibeCarousel: typeof import('./components')['VibeCarousel']
    VibeChartBar: typeof import('./components')['VibeChartBar']
    VibeChartLine: typeof import('./components')['VibeChartLine']
    VibeChartPie: typeof import('./components')['VibeChartPie']
    VibeCloseButton: typeof import('./components')['VibeCloseButton']
    VibeCol: typeof import('./components')['VibeCol']
    VibeCollapse: typeof import('./components')['VibeCollapse']
    VibeContainer: typeof import('./components')['VibeContainer']
    VibeDataTable: typeof import('./components')['VibeDataTable']
    VibeDatePicker: typeof import('./components')['VibeDatePicker']
    VibeDraggable: typeof import('./components')['VibeDraggable']
    VibeDropdown: typeof import('./components')['VibeDropdown']
    VibeDroppable: typeof import('./components')['VibeDroppable']
    VibeFileInput: typeof import('./components')['VibeFileInput']
    VibeFormCheckbox: typeof import('./components')['VibeFormCheckbox']
    VibeFormDatepicker: typeof import('./components')['VibeFormDatepicker']
    VibeFormErrorSummary: typeof import('./components')['VibeFormErrorSummary']
    VibeFormGroup: typeof import('./components')['VibeFormGroup']
    VibeFormInput: typeof import('./components')['VibeFormInput']
    VibeFormRadio: typeof import('./components')['VibeFormRadio']
    VibeFormSelect: typeof import('./components')['VibeFormSelect']
    VibeFormSpinbutton: typeof import('./components')['VibeFormSpinbutton']
    VibeFormSwitch: typeof import('./components')['VibeFormSwitch']
    VibeFormTextarea: typeof import('./components')['VibeFormTextarea']
    VibeFormWysiwyg: typeof import('./components')['VibeFormWysiwyg']
    VibeHero: typeof import('./components')['VibeHero']
    VibeIcon: typeof import('./components')['VibeIcon']
    VibeInputGroup: typeof import('./components')['VibeInputGroup']
    VibeLink: typeof import('./components')['VibeLink']
    VibeListGroup: typeof import('./components')['VibeListGroup']
    VibeModal: typeof import('./components')['VibeModal']
    VibeNav: typeof import('./components')['VibeNav']
    VibeNavbar: typeof import('./components')['VibeNavbar']
    VibeNavbarBrand: typeof import('./components')['VibeNavbarBrand']
    VibeNavbarNav: typeof import('./components')['VibeNavbarNav']
    VibeNavbarToggle: typeof import('./components')['VibeNavbarToggle']
    VibeOffcanvas: typeof import('./components')['VibeOffcanvas']
    VibePagination: typeof import('./components')['VibePagination']
    VibePlaceholder: typeof import('./components')['VibePlaceholder']
    VibePopover: typeof import('./components')['VibePopover']
    VibeProgress: typeof import('./components')['VibeProgress']
    VibeResizable: typeof import('./components')['VibeResizable']
    VibeRow: typeof import('./components')['VibeRow']
    VibeScrollspy: typeof import('./components')['VibeScrollspy']
    VibeSkeleton: typeof import('./components')['VibeSkeleton']
    VibeSlider: typeof import('./components')['VibeSlider']
    VibeSortable: typeof import('./components')['VibeSortable']
    VibeSpinner: typeof import('./components')['VibeSpinner']
    VibeStepper: typeof import('./components')['VibeStepper']
    VibeTab: typeof import('./components')['VibeTab']
    VibeTabContent: typeof import('./components')['VibeTabContent']
    VibeTabs: typeof import('./components')['VibeTabs']
    VibeToast: typeof import('./components')['VibeToast']
    VibeToastHost: typeof import('./components')['VibeToastHost']
    VibeTooltip: typeof import('./components')['VibeTooltip']
  }
}

export {}
